name: "AIGRC - AI Governance Compliance Check"
description: "Scan your codebase for AI/ML frameworks and validate compliance with governance policies"
author: "AIGRC"
branding:
  icon: "shield"
  color: "green"

inputs:
  directory:
    description: "Directory to scan (relative to workspace)"
    required: false
    default: "."
  governance-lock:
    description: "Path to governance.lock file (relative to directory)"
    required: false
    default: "governance.lock"
  check-policy:
    description: "Check code against governance.lock policy constraints"
    required: false
    default: "true"
  fail-on-violations:
    description: "Fail if policy violations are found"
    required: false
    default: "true"
  fail-on-warnings:
    description: "Fail on policy warnings (in addition to errors)"
    required: false
    default: "false"
  upload-sarif:
    description: "Upload SARIF report to GitHub Security tab"
    required: false
    default: "true"
  fail-on-high-risk:
    description: "Fail the action if high-risk AI assets are detected"
    required: false
    default: "true"
  fail-on-unregistered:
    description: "Fail if AI frameworks are detected without corresponding asset cards"
    required: false
    default: "false"
  validate-cards:
    description: "Validate all asset cards"
    required: false
    default: "true"
  create-pr-comment:
    description: "Create a PR comment with the scan results"
    required: false
    default: "true"
  github-token:
    description: "GitHub token for creating PR comments"
    required: false
    default: ${{ github.token }}
  push:
    description: "Push governance events to AIGOS"
    required: false
    default: "false"
  push-on:
    description: "When to push events (pr|merge|always|never)"
    required: false
    default: "pr"
  aigos-api-url:
    description: "AIGOS API URL for event push"
    required: false
  aigos-org-id:
    description: "Organization ID for AIGOS event push"
    required: false

outputs:
  detections-count:
    description: "Number of AI/ML framework detections found"
  high-confidence-count:
    description: "Number of high-confidence detections"
  risk-level:
    description: "Highest risk level detected (minimal, limited, high, unacceptable)"
  cards-valid:
    description: "Whether all asset cards are valid"
  cards-count:
    description: "Number of asset cards found"
  scan-results:
    description: "Full scan results as JSON"
  governance-lock-valid:
    description: "Whether governance.lock is valid and not expired"
  policy-violations:
    description: "Number of policy violations found"
  policy-errors:
    description: "Number of policy errors (blocking)"
  policy-warnings:
    description: "Number of policy warnings (non-blocking unless fail-on-warnings)"
  policy-passed:
    description: "Whether policy check passed"
  sarif-path:
    description: "Path to generated SARIF file (if upload-sarif enabled)"
  push-status:
    description: "Event push status (success|skipped|failed)"
  push-accepted:
    description: "Number of events accepted by AIGOS"
  push-rejected:
    description: "Number of events rejected by AIGOS"
  aigos-dashboard-url:
    description: "AIGOS dashboard URL for this organization"

runs:
  using: "node20"
  main: "dist/index.js"
